name: "Publish Dev Container Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Publish Features to GHCR
        run: devcontainer features publish --namespace ghcr.io/${{ github.repository }} --base-path ./src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
